x <- rbinom(100, 50, 0.8)
N <- length(x)
x.iter <- c(NA, x[1:(N-1)])
x.MR <- abs(x-x.iter)
x.AMR <- mean(x.MR, na.rm = TRUE)
x.mean <- mean(x)
x.sd <- sd(x)
UCL1 <- x.mean + 3*(x.AMR/1.128)
LCL1 <- x.mean - 3*(x.AMR/1.128)
plot(x, ylim = c(28, 51))
lines(x)
abline(h = x.mean, col = "blue")
abline(h= UCL1, col = "red")
abline(h = LCL1, col = "red")
